### ISSUE TITLE
local class incompatible: stream classdesc serialVersionUID = 5140445576767494002

### ISSUE THREAD

**Issue by hill-hu** [yunjhongwu/dl4j-vgg#1]
Hello,My d4j version is 0.7.1,Its incompatible for loading layer:
Exception in thread "main" java.io.InvalidClassException: org.deeplearning4j.nn.updater.MultiLayerUpdater; local class incompatible: stream classdesc serialVersionUID = 5140445576767494002, local class serialVersionUID = -3950052344097982845
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:222)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:299)

**Comment by yunjhongwu** [comment]
I have updated the serialized models. Now they are compatible with dl4j 0.7.2 (as well as 0.7.1).
